"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import dynamic from "next/dynamic";
import {Box,Brush,ChevronDown,Download,FolderOpen,GitBranch,ImagePlus,Layers,LogOut,Palette,Redo2,Save,Settings,Smile,Sparkles,Undo2,Upload,Move3D,Grid3X3} from "lucide-react";
const Stage=dynamic(()=>import("./stage"),{ssr:false});
const SketchStudio=dynamic(()=>import("./sketch"),{ssr:false});
type Tab="model"|"paint"|"rig"|"sketch"|"assets";
type Part={id:string;name:string;kind:string;visible:boolean;color:string;scale:number};
type Rig={mode:boolean;head:number;neck:number;spine:number;armL:number;armR:number;legL:number;legR:number;jaw:number;blink:number};
const initial:Part[]=[{id:"head",name:"Kepala",kind:"head",visible:true,color:"#f4c7aa",scale:1},{id:"hair",name:"Rambut",kind:"hair",visible:true,color:"#30213f",scale:1.05},{id:"eyes",name:"Mata",kind:"eyes",visible:true,color:"#6f55d9",scale:1},{id:"body",name:"Badan",kind:"body",visible:true,color:"#7c4dff",scale:1},{id:"accessory",name:"Aksesori",kind:"accessory",visible:true,color:"#ffb347",scale:1}];
const defaultRig:Rig={mode:false,head:0,neck:0,spine:0,armL:0,armR:0,legL:0,legR:0,jaw:0,blink:0};
const sampleModels=[
 {name:"Seed-san · CC0",url:"https://raw.githubusercontent.com/vrm-c/vrm-specification/master/samples/Seed-san/vrm/Seed-san.vrm",source:"VRM Consortium"},
 {name:"VRM Constraint Sample",url:"https://raw.githubusercontent.com/pixiv/three-vrm/dev/packages/three-vrm/examples/models/VRM1_Constraint_Twist_Sample.vrm",source:"pixiv / three-vrm"}
];
export default function Home(){
 const [locked,setLocked]=useState(true),[pw,setPw]=useState(""),[tab,setTab]=useState<Tab>("model");
 const [parts,setParts]=useState(initial),[selected,setSelected]=useState("head"),[project,setProject]=useState("Karakter Baru"),[rig,setRig]=useState(defaultRig);
 const [expression,setExpression]=useState("Neutral"),[vrmUrl,setVrmUrl]=useState<string|null>(null),[vrmName,setVrmName]=useState("Built-in Character");
 const fileRef=useRef<HTMLInputElement>(null);
 const selectedPart=useMemo(()=>parts.find(p=>p.id===selected)||parts[0],[parts,selected]);
 useEffect(()=>{setLocked(localStorage.getItem("vtuber-unlocked")!=="1");try{const d=JSON.parse(localStorage.getItem("vtuber-draft")||"null");if(d){setProject(d.project||"Karakter Baru");setParts(d.parts||initial);setRig(d.rig||defaultRig);setExpression(d.expression||"Neutral")}}catch{}},[]);
 const login=()=>{if(pw==="123456789"){localStorage.setItem("vtuber-unlocked","1");setLocked(false)}};
 const save=()=>localStorage.setItem("vtuber-draft",JSON.stringify({project,parts,rig,expression,vrmUrl,vrmName}));
 const applyExpression=(name:string)=>{setExpression(name);const p:Record<string,Partial<Rig>>={Neutral:{jaw:0,blink:0,head:0},Happy:{jaw:18,blink:0,head:3},Angry:{jaw:-4,blink:12,head:-5},Sad:{jaw:4,blink:22,head:6},Surprised:{jaw:28,blink:0,head:0},Wink:{jaw:5,blink:70,head:0}};setRig(r=>({...r,...p[name]}))};
 const importModel=(f:File)=>{const u=URL.createObjectURL(f);setVrmUrl(u);setVrmName(f.name);setTab("model")};
 if(locked)return <main className="gate"><div className="gate-orbit one"/><div className="gate-orbit two"/><div className="gate-card"><div className="logo"><Sparkles/></div><p className="eyebrow">VTUBER FORGE · STUDIO</p><h1>Bangun karakter yang terasa hidup.</h1><p className="muted">Studio karakter 3D ringan: import VRM, atur rig, gambar sketsa, dan siapkan avatar dari browser.</p><input autoFocus type="password" placeholder="Masukkan password studio" value={pw} onChange={e=>setPw(e.target.value)} onKeyDown={e=>e.key==="Enter"&&login()}/><button className="primary wide" onClick={login}>Masuk ke Studio</button><small>Studio privat · password awal: 123456789</small></div></main>;
 return <main className="app">
  <header className="topbar"><div className="brand"><div className="brand-mark"><Sparkles size={18}/></div><div><b>VTUBER FORGE</b><span>Next.js · TypeScript · Three.js · VRM</span></div></div><div className="project-name"><span className="project-dot"/><input value={project} onChange={e=>setProject(e.target.value)}/><ChevronDown size={15}/></div><div className="actions"><button title="Undo"><Undo2/></button><button title="Redo"><Redo2/></button><i/><button title="Buka"><FolderOpen/></button><button title="Import VRM" onClick={()=>fileRef.current?.click()}><Upload/></button><button title="Simpan" onClick={save}><Save/></button><button title="Ekspor"><Download/></button><button title="Keluar" onClick={()=>{localStorage.removeItem("vtuber-unlocked");location.reload()}}><LogOut/></button><input ref={fileRef} hidden type="file" accept=".vrm,.glb,.gltf" onChange={e=>{const f=e.target.files?.[0];if(f)importModel(f)}}/></div></header>
  <section className="workspace">
   <aside className="leftbar"><div className="tool-group"><small>CREATE</small><button className={tab==="model"?"active":""} onClick={()=>setTab("model")}><Box/><span>Model</span></button><button className={tab==="paint"?"active":""} onClick={()=>setTab("paint")}><Brush/><span>Paint</span></button><button className={tab==="sketch"?"active":""} onClick={()=>setTab("sketch")}><Grid3X3/><span>Sketsa</span></button><button className={tab==="assets"?"active":""} onClick={()=>setTab("assets")}><ImagePlus/><span>Asset</span></button></div><div className="tool-group"><small>CHARACTER</small><button className={tab==="rig"?"active rig-active":""} onClick={()=>setTab("rig")}><GitBranch/><span>Rigging</span></button><button><Layers/><span>Pose</span></button><button><Smile/><span>Face</span></button><button><Move3D/><span>Transform</span></button></div><div className="spacer"/><button><Settings/><span>Pengaturan</span></button></aside>
   <section className="viewport">{tab==="sketch"?<SketchStudio/>:<><div className="viewport-tools"><div><span className="pill"><span className="dot"/> LIVE 3D</span><span className="scene-label">{tab==="rig"?"RIG MODE":"CHARACTER MODE"}</span></div><span className="hint">Klik karakter · scroll zoom · drag orbit</span></div><Stage parts={parts} selected={selected} onSelect={setSelected} rig={rig} showRig={tab==="rig"} vrmUrl={vrmUrl}/><div className="bottom-hud"><button onClick={()=>setRig(r=>({...r,mode:!r.mode}))}>{rig.mode?"Rig ON":"Rig OFF"}</button><button>Front</button><button>Orbit</button><button onClick={()=>setRig(defaultRig)}>Reset</button></div><div className="viewport-card"><b>{vrmName}</b><span>{vrmUrl?"VRM/GLB loaded":"Procedural preview"} · {tab==="rig"?"Skeleton aktif":"Preview karakter"}</span></div></>}</section>
   <aside className="inspector"><div className="panel-head"><div><p className="eyebrow">{tab==="rig"?"RIGGING":tab==="assets"?"MODEL LIBRARY":"DESAIN"}</p><h2>{tab==="model"?"Model 3D":tab==="paint"?"Paint Studio":tab==="rig"?"Rig Studio":tab==="sketch"?"Sketsa": "Asset Library"}</h2></div><Sparkles size={19}/></div>
    {tab==="assets"&&<><div className="section"><label>Import karakter sendiri</label><button className="primary wide" onClick={()=>fileRef.current?.click()}><Upload size={15}/> Import .VRM / .GLB</button><p className="mini-note">Model diproses langsung di browser. Tidak perlu upload ke server untuk preview.</p></div><div className="section"><label>Sample legal-friendly</label>{sampleModels.map(m=><button className="asset-card" key={m.url} onClick={()=>{setVrmUrl(m.url);setVrmName(m.name);setTab("model")}}><div className="asset-icon"><Box/></div><div><b>{m.name}</b><span>{m.source}</span></div><ChevronDown size={15}/></button>)}</div><div className="tip"><Sparkles size={17}/><span>Model contoh dari repositori publik harus tetap mengikuti lisensi dan kredit masing-masing.</span></div></>}
    {tab==="model"&&<><div className="section"><label>Karakter aktif</label><div className="active-model"><b>{vrmName}</b><span>{vrmUrl?"Model VRM/GLB aktif":"Model procedural"}</span></div></div><div className="section"><label>Bagian karakter</label><div className="parts">{parts.map(p=><button key={p.id} className={selected===p.id?"selected":""} onClick={()=>setSelected(p.id)}><span className="swatch" style={{background:p.color}}/><span>{p.name}</span><small>{p.visible?"ON":"OFF"}</small></button>)}</div></div><div className="section"><label>Properti {selectedPart.name}</label><div className="field"><span>Warna</span><input type="color" value={selectedPart.color} onChange={e=>setParts(parts.map(p=>p.id===selected?p={...p,color:e.target.value}:p))}/></div><div className="field"><span>Skala</span><input type="range" min=".7" max="1.35" step=".01" value={selectedPart.scale} onChange={e=>setParts(parts.map(p=>p.id===selected?{...p,scale:+e.target.value}:p))}/></div></div></>}
    {tab==="paint"&&<><div className="section"><label>Paint tools</label><div className="tool-grid"><button><Brush/>Brush</button><button><Palette/>Fill</button><button><Move3D/>Transform</button><ImagePlus/>Texture</div></div><div className="section"><label>Warna aksen</label><div className="palette">{["#ff5c7a","#ffb347","#6f55d9","#43d9b8","#4da3ff","#f5f5f5","#24212c","#101018"].map(c=><button key={c} style={{background:c}} onClick={()=>setParts(parts.map(p=>p.id===selected?{...p,color:c}:p))}/>)}</div></div></>}
    {tab==="rig"&&<><div className="rig-banner"><GitBranch size={18}/><div><b>Character Rig</b><span>Bone + Face controls</span></div><button className={"toggle "+(rig.mode?"on":"")} onClick={()=>setRig(r=>({...r,mode:!r.mode}))}><i/></button></div><div className="section"><label>Bone hierarchy</label><div className="bone-tree">{["Root / Hips","Spine","Neck","Head","Arm.L","Arm.R","Leg.L","Leg.R"].map((x,i)=><button className={"bone "+(i>0?"indent":"")} key={x}><span>●</span>{x}</button>)}</div></div><div className="section"><label>Face rig</label>{([["jaw","Jaw"],["blink","Blink"]] as const).map(([k,l])=><div className="field" key={k}><span>{l}</span><input type="range" min={k==="jaw"?-30:0} max={k==="jaw"?45:100} value={rig[k]} onChange={e=>setRig(r=>({...r,[k]:+e.target.value}))}/></div>)}</div><div className="section"><label>Expression</label><div className="expression-grid">{["Neutral","Happy","Angry","Sad","Surprised","Wink"].map(x=><button className={expression===x?"selected":""} key={x} onClick={()=>applyExpression(x)}><Smile size={14}/>{x}</button>)}</div></div></>}
   </aside>
  </section><footer><span><span className="status"/> Studio siap</span><span>TypeScript · React 19 · Three.js · VRM · WebGL</span></footer>
 </main>;
}