"use client";
import {Canvas,useFrame} from "@react-three/fiber";
import {OrbitControls,Environment,ContactShadows} from "@react-three/drei";
import {VRMLoaderPlugin,VRMUtils} from "@pixiv/three-vrm";
import {GLTFLoader} from "three/examples/jsm/loaders/GLTFLoader.js";
import {useEffect,useRef,useState} from "react";
import * as THREE from "three";
type Part={id:string;name:string;kind:string;visible:boolean;color:string;scale:number};
type Rig={mode:boolean;head:number;neck:number;spine:number;armL:number;armR:number;legL:number;legR:number;jaw:number;blink:number};
function Bone({a,b,rotation=0,color="#b98cff"}:{a:[number,number,number];b:[number,number,number];rotation?:number;color?:string}){const s=new THREE.Vector3(...a),e=new THREE.Vector3(...b),m=s.clone().add(e).multiplyScalar(.5),len=s.distanceTo(e);return <group position={m} rotation={[0,0,rotation]}><mesh><cylinderGeometry args={[.035,.05,len,10]}/><meshBasicMaterial color={color}/></mesh><mesh position={[0,len/2,0]}><sphereGeometry args={[.09,12,12]}/><meshBasicMaterial color={color}/></mesh></group>}
function RigOverlay({rig}:{rig:Rig}){const r=(n:number)=>n*Math.PI/180;return <group><Bone a={[0,.9,0]} b={[0,1.55,0]} rotation={r(rig.spine)}/><Bone a={[0,1.55,0]} b={[0,2,0]} rotation={r(rig.neck)}/><Bone a={[0,2,0]} b={[0,2.55,0]} rotation={r(rig.head)} color="#ff6fb5"/><Bone a={[-.05,1.62,0]} b={[-.72,1.35,0]} rotation={r(rig.armL)}/><Bone a={[.05,1.62,0]} b={[.72,1.35,0]} rotation={r(-rig.armR)}/><Bone a={[-.28,.7,0]} b={[-.48,-.05,0]} rotation={r(rig.legL)}/><Bone a={[.28,.7,0]} b={[.48,-.05,0]} rotation={r(-rig.legR)}/></group>}
function VRMModel({url}:{url:string}){const ref=useRef<THREE.Group>(null);const [model,setModel]=useState<THREE.Object3D|null>(null);useEffect(()=>{let disposed=false;const loader=new GLTFLoader();loader.register(p=>new VRMLoaderPlugin(p));loader.load(url,g=>{if(disposed)return;const vrm=g.userData.vrm;if(vrm){VRMUtils.removeUnnecessaryVertices(g.scene);VRMUtils.combineSkeletons(g.scene);vrm.scene.traverse((o:any)=>o.frustumCulled=false);setModel(vrm.scene)}else setModel(g.scene)},undefined,e=>console.error("VRM load error",e));return()=>{disposed=true}},[url]);useFrame((_,dt)=>{if(model)(model as any).userData?.vrm?.update?.(dt)});return model?<group ref={ref} position={[0,-1.15,0]} scale={[1.25,1.25,1.25]}><primitive object={model}/></group>:null}
export default function Stage({parts,selected,onSelect,rig,showRig,vrmUrl}:{parts:Part[];selected:string;onSelect:(id:string)=>void;rig:Rig;showRig:boolean;vrmUrl:string|null}){const get=(id:string)=>parts.find(p=>p.id===id);const blink=Math.max(.08,1-rig.blink/100);return <Canvas camera={{position:[0,1.35,5],fov:34}} shadows gl={{antialias:true}}><color attach="background" args={["#09080f"]}/><ambientLight intensity={1.8}/><directionalLight position={[3,5,4]} intensity={3} castShadow/><Environment preset="city"/>{vrmUrl?<VRMModel url={vrmUrl}/>:<group position={[0,-1.2,0]} rotation={[0,0,rig.spine*Math.PI/180]}><mesh position={[0,.85,0]} scale={get("body")?.scale} onClick={()=>onSelect("body")}><capsuleGeometry args={[.68,.95,8,24]}/><meshStandardMaterial color={get("body")?.color||"#7c4dff"} roughness={.55}/></mesh><mesh position={[0,2.35,0]} scale={[get("head")?.scale||1,1,1]} rotation={[0,0,rig.head*Math.PI/180]} onClick={()=>onSelect("head")}><sphereGeometry args={[1,48,32]}/><meshStandardMaterial color={get("head")?.color||"#f4c7aa"} roughness={.5}/></mesh><mesh position={[0,2.65,-.08]} scale={[1.03*(get("hair")?.scale||1),1.02*(get("hair")?.scale||1),.9*(get("hair")?.scale||1)]} onClick={()=>onSelect("hair")}><sphereGeometry args={[1.03,48,24,0,Math.PI*2,0,Math.PI*.65]}/><meshStandardMaterial color={get("hair")?.color||"#30213f"} roughness={.65}/></mesh><mesh position={[-.34,2.38,.91]} scale={[.22,.34*blink,.08]} onClick={()=>onSelect("eyes")}><sphereGeometry args={[1,32,20]}/><meshStandardMaterial color={get("eyes")?.color||"#6f55d9"} emissive={get("eyes")?.color||"#6f55d9"} emissiveIntensity={.12}/></mesh><mesh position={[.34,2.38,.91]} scale={[.22,.34*blink,.08]} onClick={()=>onSelect("eyes")}><sphereGeometry args={[1,32,20]}/><meshStandardMaterial color={get("eyes")?.color||"#6f55d9"} emissive={get("eyes")?.color||"#6f55d9"} emissiveIntensity={.12}/></mesh>{showRig&&<RigOverlay rig={rig}/>}</group>}<ContactShadows position={[0,-1.22,0]} opacity={.45} scale={6} blur={2}/><OrbitControls enablePan={false} minDistance={3.2} maxDistance={8}/></Canvas>}
